config/routes.rb
Rails.application.routes.draw do
# 顧客用
  devise_for :customers,skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  namespace :public do
    # resources :customers, only:[:show,:edit,:update]
    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'

   delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index,:update,:destroy,:create]

    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
      resources :orders, only:[:new,:show,:index,:create]


    resources :addresses, only:[:index,:edit,:create,:update,:destroy]
    resources :items, only:[:show,:index]
  end

get '/home/about' => 'public/homes#about', as: 'about'
# 管理者用


get '/admin' => 'admin/homes#top'
 namespace :admin do
    resources :order_details, only:[:update]

    resources :orders, only:[:show,:update]

    resources :customers, only:[:index,:show,:edit,:update]

    resources :genres, only:[:index,:create,:edit,:update]

    resources :items, only:[:new,:index,:create,:show,:edit,:update]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

  def create
    @model_class_name = ModelClassName.new(params[:model_class_name])

    respond_to do |wants|
      if @model_class_name.save
        flash[:notice] = 'ModelClassName was successfully created.'
        wants.html { redirect_to(@model_class_name) }
        wants.xml  { render :xml => @model_class_name, :status => :created, :location => @model_class_name }
      else
        wants.html { render :action => "new" }
        wants.xml  { render :xml => @model_class_name.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :orders
has_many :addresses
has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end

  def get_item_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width,height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details


  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment:0, payment_confirmation:1, in_production:2, preparing_to_ship:3, shipped:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { production_not_allowed:0, waiting_for_production:1, in_production:2, production_completed:3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @newcustomer = Customer.new
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephon_nunber,:is_deleted)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
  @orders = Order.all
  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_admin!, except: [:top, :about]
   #before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(resource)
  #   if current_customer
  #     root_path
  #   else
  #     admin_path
  #   end
  # end

  # def after_sign_out_path_for(resource_or_scope)
  #   if resource_or_scope == :admin
  #     new_admin_session_path
  #   else
  #     root_path
  #   end
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name,:last_name_kana,:first_name_kana,:email,:postal_code,:address,:telephon_nunber])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
# before_action :customer_state, only: [:create]

#   protected

#   def customer_state
#   @customer = Customer.find_by(email: params[:customer][:email])
#   return if !@customer
#   if @customer.valid_password?(params[:customer][:password]) && @customer.is_deleted == true
#   redirect to new_customer_registration
#   end
#   end
end

app/helpers/admain/items_helper.rb
module Admain::ItemsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/customers/edit.html.erb
<%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
<h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h1>

<div class="form-group">
  <%= f.label :id, '会員ID' %>
  <%= @customer.id %>
</div>
<div class="form-group">
  <%= f.label :last_name, '氏名' %>
  <%= f.text_field :last_name, class: 'form-control' %>
  <%= f.text_field :first_name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :last_name_kana, 'フリガナ' %>
  <%= f.text_field :last_name_kana, class: 'form-control' %>
  <%= f.text_field :first_name_kana, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :postal_code, '郵便番号' %>
  <%= f.text_field :postal_code, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :address, class: 'form-control' %>
  <%= f.text_field :address, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :telephone_number, '電話番号' %>
  <%= f.telephone_field :telephon_nunber, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :email, 'メールアドレス' %>
  <%= f.email_field :email, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :is_deleted, '会員ステータス' %>
  <%= f.radio_button :is_deleted,  false %>
  <%= f.label :is_deleted, '有効' %>
  <%= f.radio_button :is_deleted, true %>
  <%= f.label :is_deleted, '退会' %>
</div>
<div class="form-group" >
  <%= f.submit '変更を保存', class: 'btn btn-success' %>
</div>
<% end %>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>
<table>
 <thead>
   <tr>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
   </tr>
 </thead>
<tbody>
<% @customers.each do |customer| %>
 <tr>
   <td><%= customer.id %></td>
   <td><%= link_to  admin_customer_path(customer.id) do %>
   <%= customer.last_name %><%= customer.first_name %>
   <% end %>
   </td>
   <td><%= customer.email %></td>
   <td>
   <% if customer.is_deleted == false %>
   有効
   <% else %>
   退会
   <% end %>
   </td>
<% end %>
 </tr>
</tbody>
</table>

<!--ページネーション追加-->

app/views/admin/customers/show.html.erb
<h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h1>

<p>会員ID<%= @customer.id %></p>
<p>氏名<%= @customer.last_name %><%= @customer.first_name %></p>
<p>フリガナ<%= @customer.last_name_kana %><%= @customer.first_name_kana %></p>
<p>郵便番号<%= @customer.postal_code %></p>
<p>住所<%= @customer.address %></p>
<p>電話番号<%= @customer.telephon_nunber %></p>
<p>メールアドレス<%= @customer.email %></p>
<p>会員ステータス
<% if @customer.is_deleted == false %>
有効
<% else %>
退会
<% end %>
</p>

<%= link_to "編集する",edit_admin_customer_path(@customer.id), class: "btn btn-sm btn-success edit_admin_customer_path(customer.id)" %>
<%= link_to "注文履歴一覧を見る",admin_path, class: "btn btn-sm btn-success admin_path" %>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>