config/routes.rb
Rails.application.routes.draw do
# 顧客用
  devise_for :customers,skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  namespace :public do
    # resources :customers, only:[:show,:edit,:update]
    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'

   delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index,:update,:destroy,:create]

    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
      resources :orders, only:[:new,:show,:index,:create]


    resources :addresses, only:[:index,:edit,:create,:update,:destroy]
    resources :items, only:[:show,:index]
  end

get '/home/about' => 'public/homes#about', as: 'about'
# 管理者用


get '/admin' => 'admin/homes#top'
 namespace :admin do
    resources :order_details, only:[:update]

    resources :orders, only:[:show,:update]

    resources :customers, only:[:index,:show,:edit,:update]

    resources :genres, only:[:index,:create,:edit,:update]

    resources :items, only:[:new,:index,:create,:show,:edit,:update]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

  def create
    @model_class_name = ModelClassName.new(params[:model_class_name])

    respond_to do |wants|
      if @model_class_name.save
        flash[:notice] = 'ModelClassName was successfully created.'
        wants.html { redirect_to(@model_class_name) }
        wants.xml  { render :xml => @model_class_name, :status => :created, :location => @model_class_name }
      else
        wants.html { render :action => "new" }
        wants.xml  { render :xml => @model_class_name.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :orders
has_many :addresses
has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end

  def get_item_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width,height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details


  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment:0, payment_confirmation:1, in_production:2, preparing_to_ship:3, shipped:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { production_not_allowed:0, waiting_for_production:1, in_production:2, production_completed:3 }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
  @orders = Order.all
  
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page])
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_admin!, except: [:top, :about]
   #before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(resource)
  #   if current_customer
  #     root_path
  #   else
  #     admin_path
  #   end
  # end

  # def after_sign_out_path_for(resource_or_scope)
  #   if resource_or_scope == :admin
  #     new_admin_session_path
  #   else
  #     root_path
  #   end
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name,:last_name_kana,:first_name_kana,:email,:postal_code,:address,:telephon_nunber])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
# before_action :customer_state, only: [:create]

#   protected

#   def customer_state
#   @customer = Customer.find_by(email: params[:customer][:email])
#   return if !@customer
#   if @customer.valid_password?(params[:customer][:password]) && @customer.is_deleted == true
#   redirect to new_customer_registration
#   end
#   end
end

app/helpers/admain/items_helper.rb
module Admain::ItemsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/homes/top.html.erb
<h1>注文履歴一覧</h1>
<table class="table">
 <thead>
   <tr>
    <th scope="col">購入日時</th>
    <th scope="col">購入者</th>
    <th scope="col">注文個数</th>
    <th scope="col">注文ステータス</th>
   </tr>
 </thead>
 <tbody>
 <% @orders.each do |order| %>
  <tr>
   <td scope="row"><%= link_to   order.created_at.strftime("%Y/%m/%d %H:%M:%S"),admin_order_path(order.id) %></td>
   <td scope="row"><%= order.name %></td>
   <td scope="row"><%= order.order_details.sum(:amount) %></td>
   <td scope="row"><%= order.status_i18n %></td>
  </tr>
 <% end %>
 </tbody>
</table>
<!--</%= paginate @orders %>-->

app/views/admin/items/create.html.erb
<h1>Admain::Items#create</h1>
<p>Find me in app/views/admain/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
<%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>

<div class="form-group">
  <%= f.label :item_image, '商品画像' %>
  <%= f.file_field :image, accept: "image/*", class:'form-control' %>
</div>
<div class="form-group">
  <%= f.label :name, '商品名' %>
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :introduction, '商品説明' %>
  <%= f.text_field :introduction, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :genre_id, 'ジャンル' %>
  <%= f.collection_select(:genre_id, @genres, :id, :name) %>
</div>
<div class="form-group">
  <%= f.label :price, '税抜価格' %>
  <%= f.number_field :price, class: 'form-control' %>
</div>
<div>
<p>販売ステータス</p>
 <%= f.radio_button :is_active,true %>
 <%= f.label :is_active, '販売中' %>
 <%= f.radio_button :is_active, true %>
 <%= f.label :is_active, '販売停止中' %>
</div>
<div class="form-group">
  <%= f.submit '変更を保存', class: 'btn btn-success' %>
</div>
<% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<button type="button" class="btn btn-light rounded-circle p-0" style="width:2rem;height:2rem;">
 <%= link_to "+" , new_admin_item_path %>
</button>

<table class="table">
 <thead>
    <tr>
    <th scope="col">商品ID</th>
    <th scope="col">商品名</th>
    <th scope="col">税抜価格</th>
    <th scope="col">ジャンル</th>
    <th scope="col">ステータス</th>
    </tr>
 </thead>
 <tbody>
<% @items.each do |item| %>
  <tr>
    <td scope="row"><%= item.id %></td>
    <td scope="row"><%= link_to item.name, edit_admin_item_path(item.id) %></td>
    <td scope="row"><%= item.price %>円</td>
    <td scope="row"><%= item.genre.name %></td>
    <td scope="row">
      <% if item.is_active == true %>
      販売中
      <% else %>
      販売停止中
      <% end %>
      </td>
  </tr>
<% end %>
 </tbody>
</table>
<%= paginate @items %>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>
<%= form_with model: Item.new , url: admin_items_path, method: :post do |f| %>
<div>
 <%= f.label :item_image, '商品画像' %>
 <%= f.file_field :image, accept: "image/*", class: 'form-control-file' %>
</div>
<div class="form-group">
  <%= f.label :name, '商品名' %>
  <%= f.text_field :name, class: 'form-control', placeholder: "商品名" %>
</div>
<div class="form-group">
  <%= f.label :introduction, '商品説明' %>
  <%= f.text_field :introduction, class: 'form-control', placeholder: "ここに説明文を記述します"  %>
</div>
<div class="form-group">
  <%= f.label :genre_id, 'ジャンル' %>
  <%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "--選択してください--" }  %>
</div>
<div class="form-group">
  <%= f.label :price, '税抜価格' %>
  <%= f.number_field :price, class: 'form-control', placeholder: "1000" %>
</div>
<div>
<p>販売ステータス</p>
 <%= f.radio_button :is_active, true %>
 <%= f.label :is_active, '販売中' %>
 <%= f.radio_button :is_active, true %>
 <%= f.label :is_active, '販売停止中' %>
</div>

<div class="form-group">
  <%= f.submit '新規登録', class: 'btn btn-success' %>
</div>
<% end %>

app/views/admin/items/show.html.erb
<h1>商品詳細</h1>
<%= image_tag @item.get_item_image(100,100) %>
<p>商品名<%= @item.name %></p>
<p>商品説明<%= @item.introduction %></p>
<p>ジャンル<%= @item.genre.name %></p>
<p>税込価格</br>
（税抜価格）<%= (@item.price * 1.1).floor %>(<%= @item.price %>)円</p>
<p>販売ステータス
<% if @item.is_active == true %>
販売中
<% else %>
販売停止中
<% end %>
</p>

app/views/homes/about.html.erb
<h1>about</h1>
<p>ながのCAKEは全国発送可能なケーキ屋さんです。</br>お子様からお年寄りの方までお召し上がりいただけるよう、
</br>様々なバリエーションをご用意しております。</br>また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。
</br>ぜひご注文ください。</p>

app/views/homes/top.html.erb
<p>ジャンル検索</p>

<p>ようこそ、ながのCAKEへ!</br>このサイトは、ケーキ販売のECサイトになります。
</br>会員でない方も、商品の閲覧はできますが、</br>購入には会員登録が必要になります。</p>

<h2>新着商品</h2>
<!--</%= @items.each do |item| %>-->
<!--</%= image_tag @item.get_item_image(100,100) %>-->
<!--<p></%= item.name %></p>-->
<!--<p>¥</%= item.price %></p>-->
<!--</% end %>-->