config/routes.rb
Rails.application.routes.draw do
# 顧客用
  devise_for :customers,skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  namespace :public do
    # resources :customers, only:[:show,:edit,:update]
    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'

   delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index,:update,:destroy,:create]

    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
      resources :orders, only:[:new,:show,:index,:create]


    resources :addresses, only:[:index,:edit,:create,:update,:destroy]
    resources :items, only:[:show,:index]
  end

get '/home/about' => 'public/homes#about', as: 'about'
# 管理者用


get '/admin' => 'admin/homes#top'
 namespace :admin do
    resources :order_details, only:[:update]

    resources :orders, only:[:show,:update]

    resources :customers, only:[:index,:show,:edit,:update]

    resources :genres, only:[:index,:create,:edit,:update]

    resources :items, only:[:new,:index,:create,:show,:edit,:update]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

  def create
    @model_class_name = ModelClassName.new(params[:model_class_name])

    respond_to do |wants|
      if @model_class_name.save
        flash[:notice] = 'ModelClassName was successfully created.'
        wants.html { redirect_to(@model_class_name) }
        wants.xml  { render :xml => @model_class_name, :status => :created, :location => @model_class_name }
      else
        wants.html { render :action => "new" }
        wants.xml  { render :xml => @model_class_name.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :orders
has_many :addresses
has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end

  def get_item_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width,height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details


  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment:0, payment_confirmation:1, in_production:2, preparing_to_ship:3, shipped:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { production_not_allowed:0, waiting_for_production:1, in_production:2, production_completed:3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_admin!, except: [:top, :about]
   #before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(resource)
  #   if current_customer
  #     root_path
  #   else
  #     admin_path
  #   end
  # end

  # def after_sign_out_path_for(resource_or_scope)
  #   if resource_or_scope == :admin
  #     new_admin_session_path
  #   else
  #     root_path
  #   end
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name,:last_name_kana,:first_name_kana,:email,:postal_code,:address,:telephon_nunber])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
# before_action :customer_state, only: [:create]

#   protected

#   def customer_state
#   @customer = Customer.find_by(email: params[:customer][:email])
#   return if !@customer
#   if @customer.valid_password?(params[:customer][:password]) && @customer.is_deleted == true
#   redirect to new_customer_registration
#   end
#   end
end

app/helpers/admain/items_helper.rb
module Admain::ItemsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <a class="navbar-toggler" href="/">ながのCake</a>
  <nav class="navbar navbar-expand-lg  ">
   <div class="container">
   <ul class="navbar-nav">
   <% if customer_signed_in? %>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to public_customers_my_page_path, class:'nav-link ' do %>
   マイページ
   <% end %>
   </button>
   </li>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to public_items_path, class:'nav-link ' do %>
   商品一覧
   <% end %>
   </button>
   </li>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to public_cart_items_path, class:'nav-link ' do %>
   カート
   <% end %>
   </button>
   </li>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to destroy_customer_session_path, method: :delete,class:'nav-link ' do %>
   ログアウト
   <% end %>
   </button>
   </li>
   <% elsif admin_signed_in? %>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to admin_items_path, class:'nav-link ' do %>
   商品一覧
   <% end %>
   </button>
   </li>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to admin_customers_path, class:'nav-link ' do %>
   会員一覧
   <% end %>
   </button>
   </li>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to admin_path, class:'nav-link ' do %>
   注文履歴一覧
   <% end %>
   </button>
   </li>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to admin_genres_path, class:'nav-link ' do %>
   ジャンル一覧
   <% end %>
   </button>
   </li>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to destroy_admin_session_path, method: :delete,class:'nav-link ' do %>
   ログアウト
   <% end %>
   </button>
   </li>
   <% else %>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to about_path, class: 'nav-link ' do %>
   About
   <% end %>
   </button>
   </li>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to public_items_path, class: 'nav-link ' do %>
   商品一覧
   <% end %>
   </button>
   </li>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to new_customer_registration_path, class: 'nav-link ' do %>
   新規登録
   <% end %>
   </button>
   </li>
   <li>
   <button class="btn btn-sm btn-outline-secondary" type="button">
   <%= link_to new_customer_session_path, class: 'nav-link ' do %>
   ログイン
   <% end %>
   </button>
   </li>
   </li>
   </ul>
   </div>
   <% end %>
   </nav>
  </header>
    <%= yield %>
  </body>
</html>